// Auto-generated by relay-compiler. Do not edit.

import Relay

struct PokemonListRow_pokemon {
    var fragmentPointer: FragmentPointer

    init(key: PokemonListRow_pokemon_Key) {
        fragmentPointer = key.fragment_PokemonListRow_pokemon
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "PokemonListRow_pokemon",
            type: "Pokemon",
            selections: [
                .field(ReaderScalarField(
                    name: "name"
                )),
                .field(ReaderScalarField(
                    name: "number"
                ))
            ])
    }
}


extension PokemonListRow_pokemon {
    struct Data: Decodable {
        var name: String?
        var number: String?
    }
}

protocol PokemonListRow_pokemon_Key {
    var fragment_PokemonListRow_pokemon: FragmentPointer { get }
}

extension PokemonListRow_pokemon: Relay.Fragment {}
