// Auto-generated by relay-compiler. Do not edit.

import Relay

struct PokemonListRow_pokemon {
    var fragmentPointer: FragmentPointer

    init(key: PokemonListRow_pokemon_Key) {
        fragmentPointer = key.fragment_PokemonListRow_pokemon
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "PokemonListRow_pokemon",
            type: "Pokemon",
            selections: [
                .field(ReaderScalarField(
                    name: "name"
                )),
                .field(ReaderScalarField(
                    name: "number"
                ))
            ])
    }
}


extension PokemonListRow_pokemon {
    struct Data: Readable {
        var name: String?
        var number: String?

        init(from data: SelectorData) {
            name = data.get(String?.self, "name")
            number = data.get(String?.self, "number")
        }
    }
}

protocol PokemonListRow_pokemon_Key {
    var fragment_PokemonListRow_pokemon: FragmentPointer { get }
}

extension PokemonListRow_pokemon: Relay.Fragment {}
