// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct MovieInfoSection_film {
    public var fragmentPointer: FragmentPointer

    public init(key: MovieInfoSection_film_Key) {
        fragmentPointer = key.fragment_MovieInfoSection_film
    }

    public static var node: ReaderFragment {
        ReaderFragment(
            name: "MovieInfoSection_film",
            type: "Film",
            selections: [
                .field(ReaderScalarField(
                    name: "id"
                )),
                .field(ReaderScalarField(
                    name: "episodeID"
                )),
                .field(ReaderScalarField(
                    name: "title"
                )),
                .field(ReaderScalarField(
                    name: "director"
                )),
                .field(ReaderScalarField(
                    name: "releaseDate"
                ))
            ]
        )
    }
}

extension MovieInfoSection_film {
    public struct Data: Decodable, Identifiable {
        public var id: String
        public var episodeID: Int?
        public var title: String?
        public var director: String?
        public var releaseDate: String?
    }
}

public protocol MovieInfoSection_film_Key {
    var fragment_MovieInfoSection_film: FragmentPointer { get }
}

extension MovieInfoSection_film: Relay.Fragment {}

extension MovieInfoSection_film: Relay.RefetchFragment {
    public typealias Operation = MovieInfoSectionRefetchQuery
    public static var metadata: Metadata {
        RefetchMetadata(
            path: ["node"],
            identifierField: "id",
            operation: Operation.self
        )
    }
}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

extension MovieInfoSection_film_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    public func asFragment() -> RelaySwiftUI.FragmentNext<MovieInfoSection_film> {
        RelaySwiftUI.FragmentNext<MovieInfoSection_film>(self)
    }
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    public func asFragment() -> RelaySwiftUI.RefetchableFragment<MovieInfoSection_film> {
        RelaySwiftUI.RefetchableFragment<MovieInfoSection_film>(self)
    }
}
#endif