// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct MoviesListRow_film {
    public var fragmentPointer: FragmentPointer

    public init(key: MoviesListRow_film_Key) {
        fragmentPointer = key.fragment_MoviesListRow_film
    }

    public static var node: ReaderFragment {
        ReaderFragment(
            name: "MoviesListRow_film",
            type: "Film",
            selections: [
                .field(ReaderScalarField(
                    name: "id"
                )),
                .field(ReaderScalarField(
                    name: "episodeID"
                )),
                .field(ReaderScalarField(
                    name: "title"
                )),
                .field(ReaderScalarField(
                    name: "director"
                )),
                .field(ReaderScalarField(
                    name: "releaseDate"
                ))
            ]
        )
    }
}

extension MoviesListRow_film {
    public struct Data: Decodable, Identifiable {
        public var id: String
        public var episodeID: Int?
        public var title: String?
        public var director: String?
        public var releaseDate: String?
    }
}

public protocol MoviesListRow_film_Key {
    var fragment_MoviesListRow_film: FragmentPointer { get }
}
extension MoviesListRow_film: Relay.Fragment {}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI
extension MoviesListRow_film_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    public func asFragment() -> RelaySwiftUI.FragmentNext<MoviesListRow_film> {
        RelaySwiftUI.FragmentNext<MoviesListRow_film>(self)
    }
}
#endif