// Auto-generated by relay-compiler. Do not edit.

import Relay

struct MoviesListRow_film {
    var fragmentPointer: FragmentPointer

    init(key: MoviesListRow_film_Key) {
        fragmentPointer = key.fragment_MoviesListRow_film
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "MoviesListRow_film",
            type: "Film",
            selections: [
                .field(ReaderScalarField(
                    name: "id"
                )),
                .field(ReaderScalarField(
                    name: "episodeID"
                )),
                .field(ReaderScalarField(
                    name: "title"
                )),
                .field(ReaderScalarField(
                    name: "director"
                )),
                .field(ReaderScalarField(
                    name: "releaseDate"
                ))
            ])
    }
}


extension MoviesListRow_film {
    struct Data: Decodable, Identifiable {
        var id: String
        var episodeID: Int?
        var title: String?
        var director: String?
        var releaseDate: String?
    }
}

protocol MoviesListRow_film_Key {
    var fragment_MoviesListRow_film: FragmentPointer { get }
}

extension MoviesListRow_film: Relay.Fragment {}

#if canImport(RelaySwiftUI)

import RelaySwiftUI

extension MoviesListRow_film_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    func asFragment() -> RelaySwiftUI.FragmentNext<MoviesListRow_film> {
        RelaySwiftUI.FragmentNext<MoviesListRow_film>(self)
    }
}

#endif
