// Auto-generated by relay-compiler. Do not edit.

import Relay

struct ToDoItem_todo {
    var fragmentPointer: FragmentPointer

    init(key: ToDoItem_todo_Key) {
        fragmentPointer = key.fragment_ToDoItem_todo
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "ToDoItem_todo",
            type: "Todo",
            selections: [
                .field(ReaderScalarField(
                    name: "id"
                )),
                .field(ReaderScalarField(
                    name: "text"
                )),
                .field(ReaderScalarField(
                    name: "complete"
                ))
            ])
    }
}


extension ToDoItem_todo {
    struct Data: Decodable {
        var id: String
        var text: String
        var complete: Bool
    }
}

protocol ToDoItem_todo_Key {
    var fragment_ToDoItem_todo: FragmentPointer { get }
}

extension ToDoItem_todo: Relay.Fragment {}
