// Auto-generated by relay-compiler. Do not edit.

import Relay

struct ToDoItem_todo {
    var fragmentPointer: FragmentPointer

    init(key: ToDoItem_todo_Key) {
        fragmentPointer = key.fragment_ToDoItem_todo
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "ToDoItem_todo",
            selections: [
                .field(ReaderScalarField(
                    name: "id"
                )),
                .field(ReaderScalarField(
                    name: "text"
                )),
                .field(ReaderScalarField(
                    name: "complete"
                ))
            ])
    }
}


extension ToDoItem_todo {
    struct Data: Readable {
        var id: String
        var text: String
        var complete: Bool

        init(from data: SelectorData) {
            id = data.get(String.self, "id")
            text = data.get(String.self, "text")
            complete = data.get(Bool.self, "complete")
        }
    }
}

protocol ToDoItem_todo_Key {
    var fragment_ToDoItem_todo: FragmentPointer { get }
}

extension ToDoItem_todo: Relay.Fragment {}
