// Auto-generated by relay-compiler. Do not edit.

import Relay

struct MoviesTabQuery {
    var variables: Variables

    init(variables: Variables) {
        self.variables = variables
    }

    static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "MoviesTabQuery",
                type: "Root",
                selections: [
                    .fragmentSpread(ReaderFragmentSpread(
                        name: "MoviesList_films"
                    ))
                ]),
            operation: NormalizationOperation(
                name: "MoviesTabQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "allFilms",
                        args: [
                            LiteralArgument(name: "first", value: 3)
                        ],
                        storageKey: "allFilms(first:3)",
                        concreteType: "FilmsConnection",
                        plural: false,
                        selections: [
                            .field(NormalizationLinkedField(
                                name: "edges",
                                concreteType: "FilmsEdge",
                                plural: true,
                                selections: [
                                    .field(NormalizationLinkedField(
                                        name: "node",
                                        concreteType: "Film",
                                        plural: false,
                                        selections: [
                                            .field(NormalizationScalarField(
                                                name: "id"
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "episodeID"
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "title"
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "director"
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "releaseDate"
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "__typename"
                                            ))
                                        ]
                                    )),
                                    .field(NormalizationScalarField(
                                        name: "cursor"
                                    ))
                                ]
                            )),
                            .field(NormalizationLinkedField(
                                name: "pageInfo",
                                concreteType: "PageInfo",
                                plural: false,
                                selections: [
                                    .field(NormalizationScalarField(
                                        name: "endCursor"
                                    )),
                                    .field(NormalizationScalarField(
                                        name: "hasNextPage"
                                    ))
                                ]
                            ))
                        ]
                    )),
                    .handle(NormalizationHandle(
                        kind: .linked,
                        name: "allFilms",
                        args: [
                            LiteralArgument(name: "first", value: 3)
                        ],
                        handle: "connection",
                        key: "MoviesList_allFilms"
                    ))
                ]),
            params: RequestParameters(
                name: "MoviesTabQuery",
                operationKind: .query,
                text: """
query MoviesTabQuery {
  ...MoviesList_films
}

fragment MoviesListRow_film on Film {
  id
  episodeID
  title
  director
  releaseDate
}

fragment MoviesList_films on Root {
  allFilms(first: 3) {
    edges {
      node {
        id
        ...MoviesListRow_film
        __typename
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
"""))
    }
}


extension MoviesTabQuery {
    typealias Variables = EmptyVariables
}

extension MoviesTabQuery {
    struct Data: Readable, MoviesList_films_Key {
        var fragment_MoviesList_films: FragmentPointer

        init(from data: SelectorData) {
            fragment_MoviesList_films = data.get(fragment: "MoviesList_films")
        }
    }
}

extension MoviesTabQuery: Relay.Operation {}
