// Auto-generated by relay-compiler. Do not edit.

import Relay

struct MoviesListRow_film {
    var fragmentPointer: FragmentPointer

    init(key: MoviesListRow_film_Key) {
        fragmentPointer = key.fragment_MoviesListRow_film
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "MoviesListRow_film",
            type: "Film",
            selections: [
                .field(ReaderScalarField(
                    name: "id"
                )),
                .field(ReaderScalarField(
                    name: "episodeID"
                )),
                .field(ReaderScalarField(
                    name: "title"
                )),
                .field(ReaderScalarField(
                    name: "director"
                )),
                .field(ReaderScalarField(
                    name: "releaseDate"
                ))
            ])
    }
}


extension MoviesListRow_film {
    struct Data: Readable {
        var id: String
        var episodeID: Int?
        var title: String?
        var director: String?
        var releaseDate: String?

        init(from data: SelectorData) {
            id = data.get(String.self, "id")
            episodeID = data.get(Int?.self, "episodeID")
            title = data.get(String?.self, "title")
            director = data.get(String?.self, "director")
            releaseDate = data.get(String?.self, "releaseDate")
        }
    }
}

protocol MoviesListRow_film_Key {
    var fragment_MoviesListRow_film: FragmentPointer { get }
}

extension MoviesListRow_film: Relay.Fragment {}
