// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct PokemonDetailInfoSection_pokemon {
    public var fragmentPointer: FragmentPointer

    public init(key: PokemonDetailInfoSection_pokemon_Key) {
        fragmentPointer = key.fragment_PokemonDetailInfoSection_pokemon
    }

    public static var node: ReaderFragment {
        ReaderFragment(
            name: "PokemonDetailInfoSection_pokemon",
            type: "Pokemon",
            selections: [
                .field(ReaderScalarField(
                    name: "name"
                )),
                .field(ReaderScalarField(
                    name: "number"
                )),
                .field(ReaderScalarField(
                    name: "classification"
                )),
                .field(ReaderLinkedField(
                    name: "weight",
                    concreteType: "PokemonDimension",
                    plural: false,
                    selections: [
                        .field(ReaderScalarField(
                            name: "minimum"
                        )),
                        .field(ReaderScalarField(
                            name: "maximum"
                        ))
                    ]
                )),
                .field(ReaderLinkedField(
                    name: "height",
                    concreteType: "PokemonDimension",
                    plural: false,
                    selections: [
                        .field(ReaderScalarField(
                            name: "minimum"
                        )),
                        .field(ReaderScalarField(
                            name: "maximum"
                        ))
                    ]
                ))
            ]
        )
    }
}

extension PokemonDetailInfoSection_pokemon {
    public struct Data: Decodable {
        public var name: String?
        public var number: String?
        public var classification: String?
        public var weight: PokemonDimension_weight?
        public var height: PokemonDimension_height?

        public struct PokemonDimension_weight: Decodable {
            public var minimum: String?
            public var maximum: String?
        }

        public struct PokemonDimension_height: Decodable {
            public var minimum: String?
            public var maximum: String?
        }
    }
}

public protocol PokemonDetailInfoSection_pokemon_Key {
    var fragment_PokemonDetailInfoSection_pokemon: FragmentPointer { get }
}

extension PokemonDetailInfoSection_pokemon: Relay.Fragment {}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

extension PokemonDetailInfoSection_pokemon_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    public func asFragment() -> RelaySwiftUI.FragmentNext<PokemonDetailInfoSection_pokemon> {
        RelaySwiftUI.FragmentNext<PokemonDetailInfoSection_pokemon>(self)
    }
}
#endif