// Auto-generated by relay-compiler. Do not edit.

import Relay

struct PokemonDetailTypesSection_pokemon {
    var fragmentPointer: FragmentPointer

    init(key: PokemonDetailTypesSection_pokemon_Key) {
        fragmentPointer = key.fragment_PokemonDetailTypesSection_pokemon
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "PokemonDetailTypesSection_pokemon",
            selections: [
                .field(ReaderScalarField(
                    name: "types"
                )),
                .field(ReaderScalarField(
                    name: "resistant"
                )),
                .field(ReaderScalarField(
                    name: "weaknesses"
                ))
            ])
    }
}


extension PokemonDetailTypesSection_pokemon {
    struct Data: Readable {
        var types: [String?]?
        var resistant: [String?]?
        var weaknesses: [String?]?

        init(from data: SelectorData) {
            types = data.get([String?]?.self, "types")
            resistant = data.get([String?]?.self, "resistant")
            weaknesses = data.get([String?]?.self, "weaknesses")
        }
    }
}

protocol PokemonDetailTypesSection_pokemon_Key {
    var fragment_PokemonDetailTypesSection_pokemon: FragmentPointer { get }
}

extension PokemonDetailTypesSection_pokemon: Relay.Fragment {}
