import { TypeGenerator } from 'relay-compiler';
import { generate as readerGenerate } from 'relay-compiler/lib/codegen/ReaderCodeGenerator';

export const generate: TypeGenerator['generate'] = (schema, node, _options) => {
  const readerIR = readerGenerate(schema, node);
  console.log(JSON.stringify(readerIR, null, 4));
  return '// these types are autogenerated';
};

export const transforms = [];
