// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct RemoveTodoMutation {
    public var variables: Variables

    public init(variables: Variables) {
        self.variables = variables
    }

    public static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "RemoveTodoMutation",
                type: "Mutation",
                selections: [
                    .field(ReaderLinkedField(
                        name: "removeTodo",
                        args: [
                            VariableArgument(name: "input", variableName: "input")
                        ],
                        concreteType: "RemoveTodoPayload",
                        plural: false,
                        selections: [
                            .field(ReaderScalarField(
                                name: "deletedTodoId"
                            ))
                        ]
                    ))
                ]
            ),
            operation: NormalizationOperation(
                name: "RemoveTodoMutation",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "removeTodo",
                        args: [
                            VariableArgument(name: "input", variableName: "input")
                        ],
                        concreteType: "RemoveTodoPayload",
                        plural: false,
                        selections: [
                            .field(NormalizationScalarField(
                                name: "deletedTodoId"
                            )),
                            .handle(NormalizationHandle(
                                kind: .scalar,
                                name: "deletedTodoId",
                                handle: "deleteRecord",
                                key: ""
                            ))
                        ]
                    ))
                ]
            ),
            params: RequestParameters(
                name: "RemoveTodoMutation",
                operationKind: .mutation,
                text: """
mutation RemoveTodoMutation(
  $input: RemoveTodoInput!
) {
  removeTodo(input: $input) {
    deletedTodoId
  }
}
"""
            )
        )
    }
}

extension RemoveTodoMutation {
    public struct Variables: VariableDataConvertible {
        public var input: RemoveTodoInput

        public init(input: RemoveTodoInput) {
            self.input = input
        }

        public var variableData: VariableData {
            [
                "input": input
            ]
        }
    }

    public init(input: RemoveTodoInput) {
        self.init(variables: .init(input: input))
    }
}

#if canImport(RelaySwiftUI)
import RelaySwiftUI

extension RelaySwiftUI.Query.WrappedValue where O == RemoveTodoMutation {
    public func get(input: RemoveTodoInput, fetchKey: Any? = nil) -> RelaySwiftUI.Query<RemoveTodoMutation>.Result {
        self.get(.init(input: input), fetchKey: fetchKey)
    }
}
#endif

#if canImport(RelaySwiftUI)
import RelaySwiftUI

extension RelaySwiftUI.RefetchableFragment.Wrapper where F.Operation == RemoveTodoMutation {
    public func refetch(input: RemoveTodoInput) {
        self.refetch(.init(input: input))
    }
}
#endif

extension RemoveTodoMutation {
    public struct Data: Decodable {
        public var removeTodo: RemoveTodoPayload_removeTodo?

        public struct RemoveTodoPayload_removeTodo: Decodable {
            public var deletedTodoId: String
        }
    }
}

extension RemoveTodoMutation: Relay.Operation {}