// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct ToDoItem_todo {
    public var fragmentPointer: FragmentPointer

    public init(key: ToDoItem_todo_Key) {
        fragmentPointer = key.fragment_ToDoItem_todo
    }

    public static var node: ReaderFragment {
        ReaderFragment(
            name: "ToDoItem_todo",
            type: "Todo",
            selections: [
                .field(ReaderScalarField(
                    name: "id"
                )),
                .field(ReaderScalarField(
                    name: "text"
                )),
                .field(ReaderScalarField(
                    name: "complete"
                ))
            ]
        )
    }
}

extension ToDoItem_todo {
    public struct Data: Decodable, Identifiable {
        public var id: String
        public var text: String
        public var complete: Bool
    }
}

public protocol ToDoItem_todo_Key {
    var fragment_ToDoItem_todo: FragmentPointer { get }
}
extension ToDoItem_todo: Relay.Fragment {}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI
extension ToDoItem_todo_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    public func asFragment() -> RelaySwiftUI.FragmentNext<ToDoItem_todo> {
        RelaySwiftUI.FragmentNext<ToDoItem_todo>(self)
    }
}
#endif