// Auto-generated by relay-compiler. Do not edit.

import Relay

struct ToDoList_user {
    var fragmentPointer: FragmentPointer

    init(key: ToDoList_user_Key) {
        fragmentPointer = key.fragment_ToDoList_user
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "ToDoList_user",
            type: "User",
            selections: [
                .field(ReaderLinkedField(
                    name: "todos",
                    args: [
                        LiteralArgument(name: "first", value: 100)
                    ],
                    concreteType: "TodoConnection",
                    plural: false,
                    selections: [
                        .field(ReaderLinkedField(
                            name: "edges",
                            concreteType: "TodoEdge",
                            plural: true,
                            selections: [
                                .field(ReaderLinkedField(
                                    name: "node",
                                    concreteType: "Todo",
                                    plural: false,
                                    selections: [
                                        .field(ReaderScalarField(
                                            name: "id"
                                        )),
                                        .fragmentSpread(ReaderFragmentSpread(
                                            name: "ToDoItem_todo"
                                        ))
                                    ]
                                ))
                            ]
                        ))
                    ]
                ))
            ])
    }
}


extension ToDoList_user {
    struct Data: Decodable {
        var todos: TodoConnection_todos?

        struct TodoConnection_todos: Decodable {
            var edges: [TodoEdge_edges?]?

            struct TodoEdge_edges: Decodable {
                var node: Todo_node?

                struct Todo_node: Decodable, Identifiable, ToDoItem_todo_Key {
                    var id: String
                    var fragment_ToDoItem_todo: FragmentPointer
                }
            }
        }
    }
}

protocol ToDoList_user_Key {
    var fragment_ToDoList_user: FragmentPointer { get }
}

extension ToDoList_user: Relay.Fragment {}

#if swift(>=5.3) && canImport(RelaySwiftUI)

import RelaySwiftUI

extension ToDoList_user_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    func asFragment() -> RelaySwiftUI.FragmentNext<ToDoList_user> {
        RelaySwiftUI.FragmentNext<ToDoList_user>(self)
    }
}

#endif
