// Eventually this file should be autogenerated

import Relay

struct PokemonListQuery: Operation {
    var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(),
            operation: NormalizationOperation(
                name: "PokemonListQuery",
                argumentDefinitions: [],
                selections: [
                    .field(NormalizationLinkedField(
                        name: "pokemons",
                        args: [/* TODO */],
                        concreteType: "Pokemon",
                        plural: true,
                        selections: [
                            .field(NormalizationScalarField(name: "id")),
                            .field(NormalizationScalarField(name: "name")),
                            .field(NormalizationScalarField(name: "number")),
                            .field(NormalizationScalarField(name: "classification")),
                    ]))
            ]),
            params: RequestParameters(
                name: "PokemonListQuery",
                operationKind: .query,
                text: """
query PokemonListQuery {
    pokemons(first: 50) {
        id
        name
        number
        classification
    }
}
"""))
    }

    struct Variables: Encodable {
    }

    struct Response: Decodable {
        var pokemons: [Pokemon]
    }

    struct Pokemon: Decodable {
        var id: String
        var name: String?
        var number: String?
        var classification: String?
    }
}
